codecov:
  require_ci_to_pass: yes
  token: f8baf545-d745-4d99-81e7-ef7e019a1d1c
coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

install:
  pip:
    requirements.txt

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no